name: Test and Deploy Bash Script

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Bash script tests
      run: |
        # Assuming your script is named script.sh and located in the root directory
        chmod +x ./install_apache.sh
        ./install_apache.sh --test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy files to VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "/root"

    - name: Run script on remote server
      run: |
        ssh -o StrictHostKeyChecking=no user@remote-server 'bash /root/install_apache.sh'
