name: Test and Deploy Bash Script

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Bash script tests
      run: |
        chmod +x ./install_apache.sh &&  ./install_apache.sh 

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug SSH connection
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
        chmod 600 private_key
        ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "echo 'SSH Connection Successful'"

    - name: Copy files to VM
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
        chmod 600 private_key
        scp -i private_key -o StrictHostKeyChecking=no -P ${{ secrets.PORT }} install_apache.sh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/ubuntu

    - name: Run script on remote server
      run: |
        ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'sh /ubuntu/my_script.sh'
